### ISSUE TITLE
GetWxaCodeUnlimitAsync获取小程序码的接口缺少is_hyaline参数

### ISSUE THREAD

**Issue by zxz19** [JeffreySu/WxOpen#22]
目前使用获取小程序码的B接口没有is_hyaline这个参数，用以指定是否生成背景透明的小程序码

**Comment by JeffreySu** [comment]
已经修复：https://github.com/JeffreySu/WxOpen/commit/9b8193a6bff10cb26766b4511f52c555ee3c03e7
