### ISSUE TITLE
支付后获取用户 Unionid 接口没有传入open Id

### ISSUE THREAD

**Issue by fletu** [JeffreySu/WxOpen#44]
[ApiBind(NeuChar.PlatformType.WeChat_MiniProgram, "WxAppApi.GetPaidUnionidAsync", true)]
        public static async Task<WxJsonResult> GetPaidUnionidAsync(string accessTokenOrAppId, string transaction_id, string mch_id = "", string out_trade_no = "", int timeOut = Config.TIME_OUT)
     这个获取支付后获取用户 Unionid ，方法里面没有传入用户open Id,查询不出Unionid，提示缺少参数

**Comment by JeffreySu** [comment]
已经修复，非常感谢！
