### ISSUE TITLE
关于这个小程序的samlpe问题

### ISSUE THREAD

**Issue by andyfoxcs** [JeffreySu/WxOpen#7]
因为在websocket这个部分不是很熟悉，看官方例子中，把这个小程序使用web socket调用部分也写进去了，但是实际部署的时候却无法运行wss协议，请问能否指导下如何部署 ：）

**Comment by JeffreySu** [comment]
wss其实就是ws的安全证书协议版本，类似于http和https的关系，通常只要支持了https，就能支持wss。https也是小程序request接口所必须的，所以一般来讲，wss不需要特殊设置了。

**Comment by JeffreySu** [comment]
@andyfoxcs 有关WebSocket的内容已经记录在新书中，可供参考：https://item.jd.com/12220004.html
