### ISSUE TITLE
code转json的时候报错

### ISSUE THREAD

**Issue by Craft24** [JeffreySu/WxOpen#9]
`var x = await SnsApi.JsCode2JsonAsync(appId, appSecret, code);`  
这个代码用了会报这个错误  

> Senparc.Weixin.Exceptions.ErrorJsonResultException: 微信请求发生错误！错误代码：41008，说明：missing code, hints: [ req_id: QRg6ha0910s172 ]

**Comment by JeffreySu** [comment]
现在应该已经好了吧？发布的版本可以看https://github.com/JeffreySu/WeiXinMPSDK的master分支或者nuget
